version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    shm_size: '2gb'
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=
    ports:
      - 4444:4444

  gateway-reboot:
    image: mnxzyw/selenium-demo
    container_name: gateway-reboot
    depends_on:
      - selenium
    environment:
      - SD_GATEWAY_PASSWORD=123
      - SD_STANDALONE_CHROME=http://selenium:4444/wd/hub
